// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-eUkmDzP70feaYrk-3r9FgMshbS_504s',
    appId: '1:893580875542:web:256c5dd0dc3b3f3a832237',
    messagingSenderId: '893580875542',
    projectId: 'camertrip-237',
    authDomain: 'camertrip-237.firebaseapp.com',
    storageBucket: 'camertrip-237.firebasestorage.app',
    measurementId: 'G-SPPDVCSDES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhM7CX1Kin3SwsdRiojuYbGb8tewQZnH0',
    appId: '1:893580875542:android:20601e0c6a1fa07c832237',
    messagingSenderId: '893580875542',
    projectId: 'camertrip-237',
    storageBucket: 'camertrip-237.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsgaVMhV06nyWb4bpwS0SlPs9orEHgAX4',
    appId: '1:893580875542:ios:dd33b07b443ebc3a832237',
    messagingSenderId: '893580875542',
    projectId: 'camertrip-237',
    storageBucket: 'camertrip-237.firebasestorage.app',
    androidClientId: '893580875542-udln7j2fl2ljj7asr83tuiifvn9sluo3.apps.googleusercontent.com',
    iosClientId: '893580875542-28l1ipc9ebh0curdigkhcshig60divsf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gevFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsgaVMhV06nyWb4bpwS0SlPs9orEHgAX4',
    appId: '1:893580875542:ios:dd33b07b443ebc3a832237',
    messagingSenderId: '893580875542',
    projectId: 'camertrip-237',
    storageBucket: 'camertrip-237.firebasestorage.app',
    androidClientId: '893580875542-udln7j2fl2ljj7asr83tuiifvn9sluo3.apps.googleusercontent.com',
    iosClientId: '893580875542-28l1ipc9ebh0curdigkhcshig60divsf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gevFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-eUkmDzP70feaYrk-3r9FgMshbS_504s',
    appId: '1:893580875542:web:26c630c727cd69c5832237',
    messagingSenderId: '893580875542',
    projectId: 'camertrip-237',
    authDomain: 'camertrip-237.firebaseapp.com',
    storageBucket: 'camertrip-237.firebasestorage.app',
    measurementId: 'G-WQKLDERFRZ',
  );
}
